ccpp: True
quilting: &quilting True
grid_gen_method: JPgrid
print_esmf: False
nhours_fcst: 36
restart_interval: 0

halo_boundary: 4
tile: 7

# Paths
paths:
  workdir: '{n.paths.exptdir}/{cycle}'
  templates: '{n.paths.ushdir}/templates'
  ccpp_phys_suite: '{n.paths.fv3_model}/FV3/ccpp/suites'
  fv3_exec: '{n.paths.fv3_model}/tests'
  grid: '{n.paths.homerrfs}/configs/fv3_grids.yml'
  machine: '{n.paths.homerrfs}/configs/machines.yml'
  namelist: '{n.paths.homerrfs}/configs/FV3.input.yml'
  diag_tmpl: '{n.paths.ushdir}/templates/diag_table.{n.phys_pkg}'
  base_nml: '{n.paths.ushdir}/templates/input.nml.FV3'
  fixsar: '/scratch2/BMC/det/FV3SAR_pregen/grid/{n.grid_name}'
  fixam: /scratch1/NCEPDEV/global/glopara/fix/fix_am

model_config:
  # List of items to include in the model_config. Possible items can be a string
  # referencing a method in the Forecast class, or a key: value pair. If the
  # value of the key: value pair is one of (grid, config, machine), then the
  # resulting value in the model_config file will be the value of the key set in
  # those configuration files.
  - _pe_member01
  - dt_atmos: grid
  - _start_times
  - nhours_fcst: config
  - ncores_per_node: machine
  - _quilting
  - print_esmf: config
  - total_member: 1
  - RUN_CONTINUE: '.false.'
  - ENS_SPS: '.false.'
  - cpl: '.false.'
  - calendar: 'julian'
  - memuse_verbose: '.false.'
  - atmos_nthreads: 2
  - use_hyper_thread: '.false.'
  - debug_affinity: '.true.'
  - restart_interval: config
  - output_1st_tstep_rst: '.false.'
  - nfhout: 1
  - nfhmax_hf: 60
  - nfhout_hf: 1
  - nsout: -1
  - filename_base: 'dyn phys'
  - write_fsyncflag: '.false.'
  - output_file: 'netcdf'
  - write_nemsioflip: '.false.'
  - num_files: 2




# Namelist settings that depend on scripting choices
namelist:
  atmos_model_nml:
    blocksize: '{grid.blocksize}'
    ccpp_suite: '{n.phys_pkg}'
  fv_core_nml:
    layout: ['{grid.layout_x}', '{grid.layout_y}']
    npx: '{grid.nx + 1}'
    npy: '{grid.ny + 1}'
    target_lon: '{grid.lon_ctr}'
    target_lat: '{grid.lat_ctr}'
    stretch_fac: 0.999
    bc_update_interval: 6
  gfs_physics_nml:
    lsoil: 9
  namsfc:
    fnglac: "global_glacier.2x2.grb"
    fnmxic: "global_maxice.2x2.grb"
    fntsfc: "RTGSST.1982.2012.monthly.clim.grb"
    fnsnoc: "global_snoclim.1.875.grb"
    fnzorc: "igbp"
    fnalbc: "global_snowfree_albedo.bosu.t126.384.190.rg.grb"
    fnalbc2: "global_albedo4.1x1.grb"
    fnaisc: "CFSR.SEAICE.1982.2012.monthly.clim.grb"
    fntg3c: "global_tg3clim.2.6x1.5.grb"
    fnvegc: "global_vegfrac.0.144.decpercent.grb"
    fnvetc: "global_vegtype.igbp.t126.384.190.rg.grb"
    fnsotc: "global_soiltype.statsgo.t126.384.190.rg.grb"
    fnsmcc: "global_soilmgldas.t126.384.190.grb"
    fnmskh: "seaice_newland.grb"
    fntsfa: ""
    fnacna: ""
    fnsnoa: ""
    fnvmnc: "global_shdmin.0.144x0.144.grb"
    fnvmxc: "global_shdmax.0.144x0.144.grb"
    fnslpc: "global_slope.1x1.grb"
    fnabsc: "global_mxsnoalb.uariz.t126.384.190.rg.grb"


cycledep:
  link: # Format: [source, [target]] - If no target supplied, file keeps its source name]
    input:
      - ['gfs_data.tile7.halo0.nc', 'INPUT/gfs_data.nc']
      - ['sfc_data.tile7.halo0.nc', 'INPUT/sfc_data.nc']
      - ['gfs_bndy.tile7.000.nc', 'INPUT/gfs_bndy.tile7.000.nc']
      - ['gfs_bndy.tile7.006.nc', 'INPUT/gfs_bndy.tile7.006.nc']
      - ['gfs_ctrl.nc', 'INPUT/gfs_ctrl.nc']

static:
  copy: # Format: [source, [target]] - If no target supplied, file keeps its source name
    fv3_exec:
      - [fv3.exe]

  link: # Format: [source, [target]] - If no target supplied, file keeps its source name]
        # Also accepts a "callable" defined by a method in the Forecast Class.
    griddata:
      - ['C{g.res}_mosaic.halo3.nc', 'INPUT/grid_spec.nc']
      - ['C{g.res}_grid.tile{n.tile}.halo3.nc', 'INPUT/C{g.res}_grid.tile7.halo3.nc']
      - ['C{g.res}_grid.tile{n.tile}.halo{n.halo_boundary}.nc', 'INPUT/grid.tile7.halo{n.halo_boundary}.nc']
      - ['../CCN_ACTIVATE.BIN', 'CCN_ACTIVATE.BIN']
        # - ['../2019052000/model_configure', 'model_configure']
    orodata:
      - ['C{g.res}_oro_data.tile{n.tile}.halo0.nc', 'INPUT/oro_data.nc']
      - ['C{g.res}_oro_data.tile{n.tile}.halo{n.halo_boundary}.nc', 'INPUT/oro_data.tile7.halo{n.halo_boundary}.nc']
    fixam:
      - [aerosol.dat]
      - [co2historicaldata_2010.txt]
      - [co2historicaldata_2011.txt]
      - [co2historicaldata_2012.txt]
      - [co2historicaldata_2013.txt]
      - [co2historicaldata_2014.txt]
      - [co2historicaldata_2015.txt]
      - [co2historicaldata_2016.txt]
      - [co2historicaldata_2017.txt]
      - [co2historicaldata_2018.txt]
      - [co2historicaldata_glob.txt]
      - [co2monthlycyc.txt]
      - [global_h2oprdlos.f77]
      - [global_o3prdlos.f77]
      - [global_hyblev.l65.txt]
      - [global_zorclim.1x1.grb]
      - [sfc_emissivity_idx.txt]
      - [solarconstant_noaa_an.txt]
      - namsfc_files
    ccpp_phys_suite:
      - ['suite_{n.phys_pkg}.xml']
    templates:
      - ['field_table.{n.phys_pkg}', field_table]
      - [nems.configure]
      - [data_table]

