ccpp: True
quilting: &quilting True
grid_gen_method: JPgrid
print_esmf: False
nhours_fcst: 36
restart_interval: 0

halo_boundary: 4

# Paths
paths:
  ushdir: '{n.homerrfs}/ush'
  workdir: '{n.exptdir}/{cycle}'
  templates: '{n.ushdir}/templates'
  ccpp_phys_suite: '{n.homerrfs}/FV3/ccpp/suites'
  fv3_exec: '{n.fv3_model}/tests'
  grid: '{n.configdir}/fv3_grids.yml'
  machine: '{n.configdir}/fv3_grids.yml'
  namelist: '{n.configdir}/fv3_nml.yml'
  diag_tmpl: '{n.templates}/templates/fv3_diag_table.{n.phys_pkg}'
  base_nml: '{n.templates}/templates/input.nml.FV3'

model_config:
  # List of items to include in the model_config. Possible items can be a string
  # referencing a method in the Forecast class, or a key: value pair. If the
  # value of the key: value pair is one of (grid, config, machine), then the
  # resulting value in the model_config file will be the value of the key set in
  # those configuration files.
  - pe_member01
  - dt_atmos: grid
  - start_times
  - nhours_fcst: config
  - ncores_per_node: machine
  - quilting
  - print_esmf: config
  - total_member: 1
  - RUN_CONTINUE: '.false.'
  - ENS_SPS: '.false.'
  - cpl: '.false.'
  - calendar: 'julian'
  - memuse_verbose: '.false.'
  - atmos_nthreads: 2
  - use_hyper_thread: '.false.'
  - debug_affinity: '.true.'
  - restart_interval: config
  - output_1st_tstep_rst: '.false.'

cycledep:
  link: # Format: [source, [target]] - If no target supplied, file keeps its source name]
    input:
      - ['gfs_data.tile7.halo0.nc', gfs_data.nc]
      - ['sfc_data.tile7.halo0.nc', sfc_data.nc]

static:
  copy: # Format: [source, [target]] - If no target supplied, file keeps its source name
    fv3_exec:
      - [fv3_gfs.x]

  link: # Format: [source, [target]] - If no target supplied, file keeps its source name]
    fixsar:
      - ['C{n.res}_mosaic.nc', grid_spec.nc]
      - ['C{n.res}_grid.tile{n.tile_rgnl}.halo3', 'C{n.cres}_grid.tile7.nc']
      - ['C{n.res}_grid.tile{n.tile_rgnl}.halo{n.halo_boundary}', 'C{n.cres}_grid.tile{n.tile_rgnl}.halo{n.halo_boundary}.nc']
      - ['C{n.res}_oro_data.tile{n.tile_rgnl}.halo0', oro_data.nc]
      - ['C{n.res}_oro_data.tile{n.tile_rgnl}.halo{n.halo_boundary}', 'oro_data.tile{n.tile_rgnl}.halo{n.halo_boundary}.nc']
    fixam:
      - [global_climaeropac_global.txt]
      - [global_h2o_pltc.f77]
      - [global_zorclim.1x1.grb]
      - [global_sfc_emissivity_idx.txt]
      - [global_solarconstant_noaa_an.txt]
      - [fix_co2_proj/global_co2historicaldata_2010.txt]
      - [fix_co2_proj/global_co2historicaldata_2011.txt]
      - [fix_co2_proj/global_co2historicaldata_2012.txt]
      - [fix_co2_proj/global_co2historicaldata_2013.txt]
      - [fix_co2_proj/global_co2historicaldata_2014.txt]
      - [fix_co2_proj/global_co2historicaldata_2015.txt]
      - [fix_co2_proj/global_co2historicaldata_2016.txt]
      - [fix_co2_proj/global_co2historicaldata_2017.txt]
      - [fix_co2_proj/global_co2historicaldata_2018.txt]
      - [global_co2historicaldata_glob.txt]
      - [co2monthlycyc.txt]
    ccpp_phys_suite:
      - ['suite_{n.ccpp_phys_suite}.xml']
    templates:
      - ['field_table.{n.phys_pkg}', field_table]
      - [nems.configure]
      - [data_table]

